name: Build z390
on: [push]

jobs:

  build-dist:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: version
        run: |
          echo "VERSION=$(git describe)" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build z390 distribution
        run: bash/blddist
      - name: Save the distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/z390_${{ steps.version.outputs.version }}.zip

  build-libs:
    runs-on: ubuntu-latest
    needs: build-dist
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: get dist artefact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: unzip dist for use
        run: unzip z390*.zip
      - name: build libs
        run: echo ${VERSION} && z390_${VERSION}/bash/bldlib
        env:
          VERSION: ${{ needs.build-dist.outputs.VERSION }}

  run-tests:
    runs-on: ubuntu-latest
    needs: build-dist
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: get dist artefact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Install dist in dist folder
        run: |
          mkdir -p dist
          unzip z390*.zip -d dist
      - name: run tests
        run: |
          ls -l dist/z390_${VERSION}
          cp dist/z390_${VERSION}/z390.jar .
          z390test/gradlew -p z390test test 
        env:
          VERSION: ${{ needs.build-dist.outputs.VERSION }}
