name: Build z390 (Windows)
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build z390 (win)
        shell: cmd
        run: call .\BUILD.BAT