name: Build z390
on: [push]

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: version
        run: echo "version=$(git describe)" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build z390 distribution
        run: bash/blddist
      - name: Save the distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/z390_${{ steps.version.outputs.version }}.zip

  run-tests:
    runs-on: ubuntu-latest
    needs: build-dist
    steps:
      - name: get dist artefact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: unzip dist for use
        run: pwd && ls -l && unzip z390*.zip
      - name: show dir
        run: ls -l

  