name: Publish docs via GitHub Pages
on: 
  push:
    branches:
      - main
      - doc/**

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: version
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -r doc/requirements.txt
      - run: mkdocs gh-deploy --force
        env:
          Z390_VERSION: ${{ steps.version.outputs.version }}